version: '3'

services:

   backend:
      build: ./backend
      expose:
         - ${APP_SERVER_PORT}
      ports:
         - ${APP_SERVER_PORT}:5000
         - 2500:8888
      volumes:
         - ./backend/src:/opt/app/src
      command: 
         bash -c "python src/app.py & jupyter-lab  --ip=0.0.0.0 --no-browser"
   
   frontend:
      build: ./react-frontend-docker
      expose:
         - ${REACT_APP_PORT}
      environment:
         REACT_APP_PORT: ${REACT_APP_PORT}
      ports:
         - ${REACT_APP_PORT}:3000
      volumes:
         - ./react-frontend-docker/src:/app/src
      links:
         - backend
      command:
         npm run start --myVar=something